version: '3.9'

services:
  postgres:
    build: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  pgadmin:
    image: dpage/pgadmin4:6.9
    ports:
      - 8080:80
    logging:
      driver: none
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
      - pgadmin_data:/var/lib/pgadmin/
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

  backend:
    build: backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - static_django:/app/static
    depends_on:
      - postgres


volumes:
  postgres_data:
  pgadmin_data:
  static_django: